spring:
  application:
    name: graphql-playground
  graphql:
    schema:
      locations: classpath:graphql/lec15 # Location of the GraphQL schema files default is classpath:graphql
    path: /graphql
    websocket:
      path: /graphql
    graphiql: # Is a graphical interactive in-browser GraphQL IDE
      enabled: true # Not recommended for production
      path: /graphiql

logging:
  level:
    root: INFO