spring:
  application:
    name: graphql-playground
  graphql:
    schema:
      locations: classpath:graphql/lec16 # Location of the GraphQL schema files default is classpath:graphql
    path: /graphql
    websocket:
      path: /graphql
    graphiql: # Is a graphical interactive in-browser GraphQL IDE
      enabled: true # Not recommended for production
      path: /graphiql

logging:
  level:
    root: INFO

customer:
  service:
    url: http://localhost:8080/graphql
  events:
    subscription:
        url: ws://localhost:8080/graphql